#!/usr/bin/env node
/**
 * Test manual (Node `assert`, sin Jest) para scripts/lib/megabrain-index.js
 * — ver justificación de por qué no Jest en wcag-contrast.test.js (mismo
 * motivo aquí: jest.config.js solo descubre .ts/.tsx bajo src/).
 *
 * Cubre los 3 cambios obligatorios de la decisión @architect
 * (docs/ARCHITECTURE_MAP.md sección 4️⃣.1):
 *   (a) el parseo del bloque `minds:` se detiene antes de `conclave:`
 *   (b) la contención de ruta rechaza un intento de path traversal
 *   (c) MEGABRAIN_PATH no configurada → resuelve al default, y si ese
 *       default tampoco existe en disco, el script debe fallar limpio
 *       (aquí se prueba la resolución pura; el "fallar limpio" real —
 *       process.exit(1) + mensaje sin stacktrace — vive en
 *       scripts/megabrain-expert.js::assertConfigured, verificado a mano
 *       porque process.exit() no es unit-testeable sin matar el runner).
 *
 * Uso: node scripts/lib/__tests__/megabrain-index.test.js
 *      npm run test:scripts
 */

const assert = require('node:assert/strict');
const { test } = require('node:test');
const path = require('node:path');
const {
  extractMindsBlock,
  parseMindsEntries,
  toConventionalFolder,
  resolveRelativePath,
  isContainedIn,
  resolveMegabrainBase,
} = require('../megabrain-index');

// Fixture que reproduce la forma real de AGENT-INDEX.yaml: comentarios +
// minds: (con líneas has_soul/has_agent_md/status intercaladas) + conclave:
// + cargo: — en ese orden, como el archivo real verificado.
const FIXTURE_YAML = `# AGENT-INDEX.yaml
# Auto-generated by agent_index_updater.py
version: "4.1.0"
updated: "2026-08-11"

totals:
  minds: 2
  cargo: 1
  conclave: 1
  total: 4

# =============================================================================
# MINDS (L3) - Expert Mind Clones
# =============================================================================
minds:
  - id: alex-hormozi
    path: agents/persons/ALEX_HORMOZI/
    has_soul: true
    has_agent_md: true
    status: active
  - id: andrew-mai
    path: agents/persons/ANDREW_MAI/
    has_soul: true
    has_agent_md: true
    status: active

# =============================================================================
# CONCLAVE (L1) - Deliberative Agents
# =============================================================================
conclave:
  - id: critico-metodologico
    path: agents/conclave/critico-metodologico/
    status: active

# =============================================================================
# CARGO (L4) - Functional Roles
# =============================================================================
cargo:
  sales:
    - id: sds
      path: agents/cargo/sales/sds/
      status: active
`;

// ---------------------------------------------------------------------------
// (a) El bloque `minds:` se detiene antes de `conclave:` (no se traga otros
//     bloques de nivel superior, sin importar el orden en que aparezcan)
// ---------------------------------------------------------------------------

test('extractMindsBlock: incluye las entradas de minds', () => {
  const block = extractMindsBlock(FIXTURE_YAML);
  assert.match(block, /alex-hormozi/);
  assert.match(block, /andrew-mai/);
});

test('extractMindsBlock: se detiene antes de conclave: (no incluye critico-metodologico)', () => {
  const block = extractMindsBlock(FIXTURE_YAML);
  assert.doesNotMatch(block, /critico-metodologico/);
  assert.doesNotMatch(block, /conclave:/);
});

test('extractMindsBlock: se detiene antes de cargo: (no incluye sds)', () => {
  const block = extractMindsBlock(FIXTURE_YAML);
  assert.doesNotMatch(block, /\bsds\b/);
  assert.doesNotMatch(block, /cargo:/);
});

test('extractMindsBlock: sin minds: en el texto, devuelve string vacío', () => {
  assert.equal(extractMindsBlock('version: "1.0"\nconclave:\n  - id: x\n'), '');
});

test('parseMindsEntries: solo devuelve los 2 ids de minds:, con su path', () => {
  const entries = parseMindsEntries(FIXTURE_YAML);
  assert.equal(entries.size, 2);
  assert.equal(entries.get('alex-hormozi'), 'agents/persons/ALEX_HORMOZI/');
  assert.equal(entries.get('andrew-mai'), 'agents/persons/ANDREW_MAI/');
});

test('parseMindsEntries: NUNCA incluye ids de conclave: o cargo: (regresión del bug real)', () => {
  const entries = parseMindsEntries(FIXTURE_YAML);
  assert.equal(entries.has('critico-metodologico'), false);
  assert.equal(entries.has('sds'), false);
});

test('parseMindsEntries: es case-sensitive en las keys tal como vienen del YAML (lookup case-insensitive es responsabilidad de resolveRelativePath)', () => {
  const entries = parseMindsEntries(FIXTURE_YAML);
  assert.equal(entries.has('ALEX-HORMOZI'), false);
  assert.equal(entries.has('alex-hormozi'), true);
});

// ---------------------------------------------------------------------------
// toConventionalFolder + resolveRelativePath (índice vs fallback)
// ---------------------------------------------------------------------------

test('toConventionalFolder: alex-hormozi -> ALEX_HORMOZI', () => {
  assert.equal(toConventionalFolder('alex-hormozi'), 'ALEX_HORMOZI');
});

test('resolveRelativePath: id indexado usa el path del índice (fuente autoritativa)', () => {
  const entries = parseMindsEntries(FIXTURE_YAML);
  const result = resolveRelativePath('alex-hormozi', entries);
  assert.equal(result.relPath, 'agents/persons/ALEX_HORMOZI/');
  assert.equal(result.source, 'index');
});

test('resolveRelativePath: lookup case-insensitive contra el índice', () => {
  const entries = parseMindsEntries(FIXTURE_YAML);
  const result = resolveRelativePath('Alex-Hormozi', entries);
  assert.equal(result.source, 'index');
  assert.equal(result.relPath, 'agents/persons/ALEX_HORMOZI/');
});

test('resolveRelativePath: id NO indexado cae al fallback por convención', () => {
  const entries = parseMindsEntries(FIXTURE_YAML);
  const result = resolveRelativePath('jim-edwards', entries);
  assert.equal(result.source, 'fallback');
  assert.equal(result.relPath, 'agents/persons/JIM_EDWARDS/');
});

// ---------------------------------------------------------------------------
// (b) Contención de ruta rechaza path traversal
// ---------------------------------------------------------------------------

const FAKE_MEGABRAIN_BASE = path.join(__dirname, '__fixtures__', 'FakeMegabrain');
const FAKE_PERSONS_BASE = path.join(FAKE_MEGABRAIN_BASE, 'agents', 'persons');

test('isContainedIn: una carpeta legítima dentro de agents/persons/ sí queda contenida', () => {
  const candidate = path.join(FAKE_PERSONS_BASE, 'ALEX_HORMOZI');
  assert.equal(isContainedIn(FAKE_PERSONS_BASE, candidate), true);
});

test('isContainedIn: rechaza un intento de path traversal (../../../etc/passwd)', () => {
  const entries = new Map(); // id no indexado -> fuerza el fallback por convención
  const { relPath, source } = resolveRelativePath('../../../etc/passwd', entries);
  assert.equal(source, 'fallback');

  const candidate = path.resolve(FAKE_MEGABRAIN_BASE, relPath);
  assert.equal(isContainedIn(FAKE_PERSONS_BASE, candidate), false);
});

test('isContainedIn: rechaza traversal aunque el identificador use backslashes (estilo Windows)', () => {
  const entries = new Map();
  const { relPath } = resolveRelativePath('..\\..\\..\\Windows\\System32', entries);
  const candidate = path.resolve(FAKE_MEGABRAIN_BASE, relPath);
  assert.equal(isContainedIn(FAKE_PERSONS_BASE, candidate), false);
});

test('isContainedIn: una ruta hermana (mismo prefijo de string pero fuera del directorio) se rechaza', () => {
  // Regresión de un bug clásico de "startsWith" sin separador: 'persons-evil'
  // empieza con el mismo string que 'persons' pero NO es un subdirectorio.
  const evilSibling = FAKE_PERSONS_BASE + '-evil';
  assert.equal(isContainedIn(FAKE_PERSONS_BASE, evilSibling), false);
});

// ---------------------------------------------------------------------------
// (c) MEGABRAIN_PATH no configurada — resolución limpia (sin stacktrace)
// ---------------------------------------------------------------------------

test('resolveMegabrainBase: usa el default cuando MEGABRAIN_PATH no está en env', () => {
  const result = resolveMegabrainBase({}, 'C:\\Users\\Oscar\\Desktop\\Megabrain');
  assert.equal(result, path.resolve('C:\\Users\\Oscar\\Desktop\\Megabrain'));
});

test('resolveMegabrainBase: MEGABRAIN_PATH en env tiene prioridad sobre el default', () => {
  const result = resolveMegabrainBase({ MEGABRAIN_PATH: 'D:\\otra\\ruta' }, 'C:\\default');
  assert.equal(result, path.resolve('D:\\otra\\ruta'));
});

test('resolveMegabrainBase: string vacío en MEGABRAIN_PATH también cae al default (no un path vacío/relativo accidental)', () => {
  const result = resolveMegabrainBase({ MEGABRAIN_PATH: '' }, 'C:\\default');
  assert.equal(result, path.resolve('C:\\default'));
});

test('caso combinado: env sin configurar + default inexistente -> la ruta resuelta no existe (lo que dispara el "fallar limpio" en megabrain-expert.js::assertConfigured)', () => {
  const fs = require('node:fs');
  const nonExistentDefault = path.join(__dirname, '__fixtures__', 'ruta-que-no-existe-nunca');
  const resolved = resolveMegabrainBase({}, nonExistentDefault);
  assert.equal(fs.existsSync(resolved), false);
});
